### ISSUE TITLE
customView with onClick event

### ISSUE THREAD

**Issue by mrthehud** [prodz18/TiFlexiGrid#7]
Hi Pablorr,

I'm trying to get a click event to fire, but even binding to all, nothing appears to get triggered (in the iOS simulator at least). Any ideas?

I've a list of Views, each containing a single ImageView. I've tried binding the click to the view and the image view to no avail, and can't bind anything to the flex grid directly (which I don't see as a massive issue).

Nice widget otherwise though =)
Hud

**Comment by prodz18** [comment]
Hi. Can you post a sample code?

**Comment by robertovergallo** [comment]
Same problem here, also on Android.
Grid is displayed fine but nothing happens when I press on my custom view.
This is my code:

//initializing the items array
var items = [];

//creating an item: a custom view
var myCustomView = Ti.UI.createView({
        width:'99%',
        height:'99%',
        backgroundColor:'#555'
    });

//adding an event listener to the custom view
myCustomView.addEventListener('click', function(e) { //NEVER FIRED !!!
        alert('view pressed'); 
});

//creating a label and adding it to the custom view
var myLabel = Ti.UI.createLabel({
    text:'Label text',
    width:Ti.UI.SIZE,
    height:Ti.UI.SIZE,
    font: { fontSize:48 },
    color:'#dddddd'
});
myCustomView.add(myLabel);

//adding the item to the items array
items.push(myCustomView);

//create grid
$.fg.createGrid({
            columns:3,
            space:5, 
            data:items,
            layout:'customView',
            params:{
                backgroundColor: '#eee',
                gridColor: '#ccc'
            }
        });

Thanks!!
Roberto

**Comment by prodz18** [comment]
Check out update 1.2. It' should be easier now.
